### ISSUE TITLE
config.json validation

### ISSUE THREAD

**Issue by Jordan141** [michaelKurowski/lokim2#16]
Hey guys, I believe a small if statement near the start of the application to check if the config.json has been populated (say you've just created a clean workspace and forgot), before allowing the server to run with no information, then believing something could be wrong with the requests as the only response one receives on the front-end is 500; Bad Request.  This is, of course, just a quality of life improvement which can be completed in a single line of code and probably won't affect the application's overall performance. Just helps forgetful devs.

**Comment by michaelKurowski** [comment]
I'd like to make it scale-able @MarcinGrzeszczak 
Could you make it generic, in a way that we will just need to enlist obligatory fields somewhere in app, and then it will just loop through `config.json` and will check only those selected as obligatory?

**Comment by michaelKurowski** [comment]
https://github.com/michaelKurowski/lokim2/issues/22 Related
