### ISSUE TITLE
Socket.IO Extensions

### ISSUE THREAD

**Issue by Jordan141** [michaelKurowski/lokim2#38]
Extend the current message method to return the username of the person sending the message, so that recipients are able to know who sent it. 

for the JOIN method, it wouldn't be a bad idea either to give the user a list of users currently in the room, so they know who they're speaking with.

**Comment by Jordan141** [comment]
Timestamp of message would also be a nice feature, pretty easy to have it as a required field alongside the message + sender name themselves

**Comment by michaelKurowski** [comment]
> Extend the current message method to return the username of the person sending the message, so that recipients are able to know who sent it.
#30 According to documentation in this PR, this is how `message` events are supposed to work.

As for timestamps, no problem. Just change the ticket title.

**Comment by michaelKurowski** [comment]
I've decided to split the issue into 2 smaller ones:
#39 & #40
