### ISSUE TITLE
Make build system OS agnostic

### ISSUE THREAD

**Issue by michaelKurowski** [michaelKurowski/lokim2#51]
We need to replace npm scripts with OS  alternative that will work on Linux, Windows and Mac.

**Comment by michaelKurowski** [comment]
@Jordan141 Could you put here your issues with npm scripts on Windows?

**Comment by michaelKurowski** [comment]
@Jordan141 bump

**Comment by Jordan141** [comment]
### Errors found in Windows 10 Latest Build 04/09/2018

![image](https://user-images.githubusercontent.com/15958401/45050612-a4f74500-b079-11e8-89e0-cfd49ec23eac.png)

Issue is fairly similar to these sources:
- https://github.com/tylingsoft/markdown-plus/issues/89
- https://github.com/isaacs/rimraf/issues/107
- https://github.com/facebook/jest/issues/4751

Unsuccessful Fix: Installing Webpack Globally
Progress was made by changing 
```
"build-dev": "node ./node_modules/.bin/webpack...." 
to
"build-dev": "node ./node_modules/webpack/bin/webpack.js...."
```
Current Error: 'cp' is not recognized as an internal or external command in 
```
build-dev: `node ./node_modules/webpack/bin/webpack.js --config ./dev.webpack.config.js && cp ./frontEnd/src/theme/index.html ./public/`
```

**Comment by Jordan141** [comment]
### UPDATE
build-dev functions on Windows 10 after changing it to
```
"build-dev": "node ./node_modules/webpack/bin/webpack.js --config ./dev.webpack.config.js && copy .\\frontEnd\\src\\theme\\index.html .\\public\\",
```

**Comment by michaelKurowski** [comment]
@MarcinGrzeszczak This is the ticket that I've been talking about,
please check if all npm scripts from `src/server/package.json` and `src/server/frontEnd/package.json`.

**Comment by Rejzor** [comment]
#### Tested Commands
- [x] npm run build 👍 - resolved by gulp.js
- [x] npm run build-dev 👍 - resolved by gulp.js
- [x] npm test 👍- now works on WindowsOS machines, I did not check on UNIX yet. now npm test alias looks:
"test": "node ./node_modules/mocha/bin/mocha \"./.tests/mocha/**/*.spec.js*\"",
