### ISSUE TITLE
Unable to join any room

### ISSUE THREAD

**Issue by michaelKurowski** [michaelKurowski/lokim2#72]
**List of steps leading to reproduce the error**
- I run server via `npm start`
- I run frontend via `npm start`
- LokIM frontend runs on `localhost:3000`
- I log into LokIM via login page
![image](https://user-images.githubusercontent.com/2772942/39966069-de0a5a54-56a5-11e8-9134-1646103c0dc7.png)
- I have no way to connect to any room
![image](https://user-images.githubusercontent.com/2772942/39966077-0c44d35e-56a6-11e8-9c88-8c77093c3ff0.png)

**Expected result**
I should be able to join some room

**Actual result**
I don't see any option to join a room, and "Disconnected / Error" is visible on the right side.

**Logs**
Google Chrome console logs:
[localhost-1526205999574.log](https://github.com/michaelKurowski/lokim2/files/1998318/localhost-1526205999574.log)
Google Chrome network logs (only HTTP traffic):
[localhost.zip](https://github.com/michaelKurowski/lokim2/files/1998322/localhost.zip)

**Comment by Jordan141** [comment]
I believe this bug is related to the strange occurrence where the sockets don't connect until a page refresh, this one may take some time to track down the source. The problem in this issue though, is that there is no join event fired, as there is no one creating rooms at the moment. As such, there is nothing actually wrong so far, other than a create option missing, which I'll open a separate ticket for, and reference this issue.

**Comment by michaelKurowski** [comment]
@Jordan141 
Client actually receives join event upon connecting to its own private room.

**Comment by michaelKurowski** [comment]
Also, shouldn't we have button for joining room by name?

**Comment by michaelKurowski** [comment]
@Jordan141 
LokIM WebSockets Testing Tool
Seems to confirm that it's working. The event is received right after connecting to the `Room` namespace.
![image](https://user-images.githubusercontent.com/2772942/40024719-88e8ad66-57cf-11e8-9133-6de8f25624e1.png)

**Comment by Jordan141** [comment]
Fixed the issue, overreaching bug of sockets acting weird and requiring a page issue will be sorted once #35 has been completed.

**Comment by michaelKurowski** [comment]
https://github.com/michaelKurowski/lokim2/pull/76#pullrequestreview-121392080
Accoring to PR description, it fixes the issue.
