### ISSUE TITLE
GUI Room Join/Create + User Searching on Frontend

### ISSUE THREAD

**Issue by Jordan141** [michaelKurowski/lokim2#80]

**Comment by Jordan141** [comment]
Notable issues so far: 
- List users event fires to other users when I request it, but not the requester. As the one requesting the data I find this behavior to be odd. 
- Rooms user's not updating on GUI even though state has changed
- join event fires creating a new room on the GUI anytime I click on it for the other user.

Ideas so far:
- Propagate Create a Room input field with Friends list #79  to avoid invalid queries/responses.
- Do rooms have names? Should they?

**Comment by michaelKurowski** [comment]
Hows it progressing? @Jordan141 
We're soon going to start implementing friend lists on backend.

**Comment by Jordan141** [comment]
At the last time of editing, I believe I had logout working, or at least almost working. I still need to add tests for the new code.

I think it would be nice to wait for the friendslist so I can populate the "create" input field with suggestions of friends so that we don't have tons of issues where we're inviting people who don't exist/typos. Since I intend on implementing this anyway, I don't want to implement something else, then just rip it all out when friendslist is completed.

This option also heightens security, as you can only add users who are your friends to your room.

Still have an odd myriad of bugs to fix, but I have a handle on them at the moment, I'll make some progress today.

Might also be an idea to add online status to users, no use in adding an offline person to a group after all. Especially if we aren't storing room data on the server for them to be added to the room once they're online.
